### ISSUE TITLE
Need coarse of the grain and weight. 

### ISSUE THREAD

**Issue by krafts** [hypergig/cafe-devops#1]
Coarse of the grain by number and grinder mosel used. 

Grinder: Cuisinart 670
Grind number: 7
Weight: 76g
Water: 10 cups or 30 ounces
Coffee maker: technivorm moccasmaster 350
Pictures: optional. This needs to be a list.

**Comment by hypergig** [comment]
exactly the kind of data we need to record, can you create file/process for tracking for rig information
